export interface GamePreset {
  id: string;
  name: string;
  category: "sandbox" | "fps" | "rpg" | "survival" | "racing" | "classic";
  defaultPort: number;
  protocol: "tcp" | "udp" | "both";
  icon: string; // Lucide icon or emoji
  color: string;
  lanDiscoverySupported: boolean;
  discoveryPort?: number;
  description: string;
  connectHint: string;
}

export const GAME_PRESETS: GamePreset[] = [
  {
    id: "minecraft_java",
    name: "Minecraft (Java Edition)",
    category: "sandbox",
    defaultPort: 25565,
    protocol: "tcp",
    icon: "Pickaxe",
    color: "#22c55e",
    lanDiscoverySupported: true,
    discoveryPort: 4445,
    description: "Открой мир для сети в игре — сервер автоматически появится у друзей!",
    connectHint: "Сетевая игра -> Прямое подключение -> {HOST_IP}:25565",
  },
  {
    id: "terraria",
    name: "Terraria",
    category: "sandbox",
    defaultPort: 7777,
    protocol: "tcp",
    icon: "TreePine",
    color: "#10b981",
    lanDiscoverySupported: true,
    description: "Кооперативное выживание. Создай сервер через меню игры или TerrariaServer.exe.",
    connectHint: "Многопользовательская игра -> Присоединиться по IP -> {HOST_IP} -> Порт 7777",
  },
  {
    id: "palworld",
    name: "Palworld",
    category: "survival",
    defaultPort: 8211,
    protocol: "udp",
    icon: "Egg",
    color: "#3b82f6",
    lanDiscoverySupported: false,
    description: "Выживание с питомцами на выделенном или совместном локальном сервере.",
    connectHint: "Присоединиться к мультиплееру -> ввести {HOST_IP}:8211 внизу экрана",
  },
  {
    id: "cs_source",
    name: "Counter-Strike / Source Games",
    category: "fps",
    defaultPort: 27015,
    protocol: "udp",
    icon: "Crosshair",
    color: "#f59e0b",
    lanDiscoverySupported: true,
    discoveryPort: 27015,
    description: "CS 1.6, CS:Source, Half-Life 2, Left 4 Dead 2, Garry's Mod.",
    connectHint: "В консоли игры: connect {HOST_IP}:27015 или вкладка LAN в Find Servers",
  },
  {
    id: "valheim",
    name: "Valheim",
    category: "survival",
    defaultPort: 2456,
    protocol: "udp",
    icon: "Shield",
    color: "#eab308",
    lanDiscoverySupported: false,
    description: "Скандинавский кооперативный симулятор выживания в чистилище.",
    connectHint: "Start Game -> Start Server / Присоединиться по IP -> {HOST_IP}:2456",
  },
  {
    id: "stardew_valley",
    name: "Stardew Valley",
    category: "sandbox",
    defaultPort: 24642,
    protocol: "udp",
    icon: "Sprout",
    color: "#ec4899",
    lanDiscoverySupported: true,
    description: "Уютная фермерская RPG для 1-8 игроков.",
    connectHint: "Совместная игра -> Вступить в игру по LAN -> {HOST_IP}",
  },
  {
    id: "factorio",
    name: "Factorio",
    category: "sandbox",
    defaultPort: 34197,
    protocol: "udp",
    icon: "Cpu",
    color: "#f97316",
    lanDiscoverySupported: true,
    discoveryPort: 34197,
    description: "Автоматизация и строительство фабрик. Полная поддержка автопоиска LAN!",
    connectHint: "Сетевая игра -> Локальная игра (LAN) или Подключиться к адресу -> {HOST_IP}:34197",
  },
  {
    id: "project_zomboid",
    name: "Project Zomboid",
    category: "survival",
    defaultPort: 16261,
    protocol: "udp",
    icon: "Skull",
    color: "#ef4444",
    lanDiscoverySupported: false,
    description: "Хардкорное выживание во время зомби-апокалипсиса.",
    connectHint: "Войти на сервер -> Добавить сервер -> IP: {HOST_IP}, Порт: 16261",
  },
  {
    id: "dont_starve",
    name: "Don't Starve Together",
    category: "survival",
    defaultPort: 10999,
    protocol: "udp",
    icon: "Flame",
    color: "#d97706",
    lanDiscoverySupported: true,
    description: "Выживайте вместе в темном процедурно-генерируемом мире.",
    connectHint: "Просмотр игр -> Фильтр: Только LAN -> Сервер хоста появится в списке",
  },
  {
    id: "homm3",
    name: "Heroes of Might and Magic III",
    category: "classic",
    defaultPort: 2300,
    protocol: "both",
    icon: "Crown",
    color: "#a855f7",
    lanDiscoverySupported: true,
    description: "Легендарная пошаговая стратегия (HotA / HD Mod). TCP/IP игра.",
    connectHint: "Новая игра -> Многопользовательская -> TCP/IP -> Ввести {HOST_IP}",
  },
  {
    id: "assetto_corsa",
    name: "Assetto Corsa",
    category: "racing",
    defaultPort: 9600,
    protocol: "both",
    icon: "Gauge",
    color: "#06b6d4",
    lanDiscoverySupported: false,
    description: "Реалистичный автосимулятор. Сервер поднимается через acServer.exe.",
    connectHint: "Content Manager -> Drive -> LAN -> Сервер хоста",
  },
  {
    id: "worms_armageddon",
    name: "Worms Armageddon",
    category: "classic",
    defaultPort: 17011,
    protocol: "tcp",
    icon: "Bomb",
    color: "#84cc16",
    lanDiscoverySupported: true,
    description: "Культовая битва червячков с базуками и банана-бомбами по Direct IP.",
    connectHint: "Сетевая игра -> Direct IP -> Ввести {HOST_IP}",
  },
];
