# Game presets catalog for LANForge GUI
GAME_PRESETS = [
    {
        "id": "minecraft_java",
        "name": "Minecraft (Java Edition)",
        "category": "Песочницы",
        "default_port": 25565,
        "protocol": "TCP",
        "color": "#22c55e",
        "lan_discovery": True,
        "description": "Открой мир для сети в игре — сервер автоматически появится у друзей во вкладке Локальная игра!",
        "hint": "Сетевая игра -> Прямое подключение -> {HOST_IP}:25565",
    },
    {
        "id": "terraria",
        "name": "Terraria",
        "category": "Песочницы",
        "default_port": 7777,
        "protocol": "TCP",
        "color": "#10b981",
        "lan_discovery": True,
        "description": "Кооперативное 2D выживание. Создай сервер через меню игры или TerrariaServer.exe.",
        "hint": "Многопользовательская игра -> Присоединиться по IP -> {HOST_IP} -> Порт 7777",
    },
    {
        "id": "palworld",
        "name": "Palworld",
        "category": "Выживание",
        "default_port": 8211,
        "protocol": "UDP",
        "color": "#3b82f6",
        "lan_discovery": False,
        "description": "Выживание с питомцами на выделенном или совместном локальном сервере.",
        "hint": "Присоединиться к мультиплееру -> ввести {HOST_IP}:8211 внизу экрана",
    },
    {
        "id": "cs_source",
        "name": "Counter-Strike / Source Games",
        "category": "Шутеры",
        "default_port": 27015,
        "protocol": "UDP",
        "color": "#f59e0b",
        "lan_discovery": True,
        "description": "CS 1.6, CS:Source, Half-Life 2, Left 4 Dead 2, Garry's Mod.",
        "hint": "В консоли игры: connect {HOST_IP}:27015 или вкладка LAN в Find Servers",
    },
    {
        "id": "valheim",
        "name": "Valheim",
        "category": "Выживание",
        "default_port": 2456,
        "protocol": "UDP",
        "color": "#eab308",
        "lan_discovery": False,
        "description": "Скандинавский кооперативный симулятор выживания в процедурном мире.",
        "hint": "Start Game -> Start Server / Присоединиться по IP -> {HOST_IP}:2456",
    },
    {
        "id": "stardew_valley",
        "name": "Stardew Valley",
        "category": "Песочницы",
        "default_port": 24642,
        "protocol": "UDP",
        "color": "#ec4899",
        "lan_discovery": True,
        "description": "Уютная фермерская RPG для совместной игры до 8 человек.",
        "hint": "Совместная игра -> Вступить в игру по LAN -> {HOST_IP}",
    },
    {
        "id": "factorio",
        "name": "Factorio",
        "category": "Песочницы",
        "default_port": 34197,
        "protocol": "UDP",
        "color": "#f97316",
        "lan_discovery": True,
        "description": "Автоматизация и строительство фабрик. Полная поддержка автопоиска LAN!",
        "hint": "Сетевая игра -> Локальная игра (LAN) или Подключиться к адресу -> {HOST_IP}:34197",
    },
    {
        "id": "project_zomboid",
        "name": "Project Zomboid",
        "category": "Выживание",
        "default_port": 16261,
        "protocol": "UDP",
        "color": "#ef4444",
        "lan_discovery": False,
        "description": "Хардкорное выживание во время зомби-апокалипсиса с друзьями.",
        "hint": "Войти на сервер -> Добавить сервер -> IP: {HOST_IP}, Порт: 16261",
    },
    {
        "id": "dont_starve",
        "name": "Don't Starve Together",
        "category": "Выживание",
        "default_port": 10999,
        "protocol": "UDP",
        "color": "#d97706",
        "lan_discovery": True,
        "description": "Выживайте вместе в темном процедурно-генерируемом мире.",
        "hint": "Просмотр игр -> Фильтр: Только LAN -> Сервер хоста появится в списке",
    },
    {
        "id": "homm3",
        "name": "Heroes of Might and Magic III",
        "category": "Классика",
        "default_port": 2300,
        "protocol": "TCP",
        "color": "#a855f7",
        "lan_discovery": True,
        "description": "Легендарная пошаговая стратегия (HotA / HD Mod). Прямая TCP/IP игра.",
        "hint": "Новая игра -> Многопользовательская -> TCP/IP -> Ввести {HOST_IP}",
    },
    {
        "id": "worms_armageddon",
        "name": "Worms Armageddon",
        "category": "Классика",
        "default_port": 17011,
        "protocol": "TCP",
        "color": "#84cc16",
        "lan_discovery": True,
        "description": "Культовая битва червячков с базуками и банана-бомбами по Direct IP.",
        "hint": "Сетевая игра -> Direct IP -> Ввести {HOST_IP}",
    },
    {
        "id": "assetto_corsa",
        "name": "Assetto Corsa",
        "category": "Классика",
        "default_port": 9600,
        "protocol": "BOTH",
        "color": "#06b6d4",
        "lan_discovery": False,
        "description": "Реалистичный автосимулятор. Сервер поднимается через acServer.exe.",
        "hint": "Content Manager -> Drive -> LAN -> Сервер хоста",
    },
]
